# Generated by Django 2.0.5 on 2022-02-19 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='creaet_time',
            new_name='create_time',
        ),
    ]
